/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./../src/components/AppLink/index.vue')['default']
    Card: typeof import('./../src/components/Card/index.vue')['default']
    Logo: typeof import('./../src/components/Logo/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    ThemeSwitcher: typeof import('./../src/components/ThemeSwitcher/index.vue')['default']
  }
}

// For TSX support
declare global {
  const AppLink: typeof import('./../src/components/AppLink/index.vue')['default']
  const Card: typeof import('./../src/components/Card/index.vue')['default']
  const Logo: typeof import('./../src/components/Logo/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
  const ThemeSwitcher: typeof import('./../src/components/ThemeSwitcher/index.vue')['default']
}