/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./../src/components/AppLink/index.vue')['default']
    Card: typeof import('./../src/components/Card/index.vue')['default']
    Logo: typeof import('./../src/components/Logo/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    ThemeSwitcher: typeof import('./../src/components/ThemeSwitcher/index.vue')['default']
  }
}
